config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :teams do
    resources :players do
      resources :hits, :only => [:create, :destroy]
    end
  end
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :player
  belongs_to :hit_type
end

app/models/hit_type.rb
class HitType < ActiveRecord::Base
  has_many :hits
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :hits
  belongs_to :team

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def batting_average(hits, at_bats)
    ".#{(sprintf "%.3f", (hits.to_f / at_bats.to_f).round(3)).split('.')[1]}"
  end

  def slugging(singles, doubles, triples, homeruns, at_bats)
    ".#{(sprintf "%.3f", (singles + (doubles * 2) + (triples * 3) + (homeruns * 4)).to_f / at_bats.to_f).split('.')[1]}"
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players

  geocoded_by :address
  after_validation :geocode

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  has_attached_file :stadium_chart, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :stadium_chart, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController

  def create
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:player_id])
    @hit = @player.hits.create(hit_params)
    respond_to do |format|
      format.html { redirect_to team_player_path(@team, @player) }
      format.js
    end
  end

  def destroy
    @player = Player.find(params[:player_id])
    @hit = Hit.find(params[:id])
    @hit.destroy

    respond_to do |format|
      format.html { redirect_to team_player_path(@team, @player) }
      format.js
    end

  end

private
  def hit_params
    params.require(:hit).permit(:coords, :hit_type_id)
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    @hit = Hit.new
    @hit_types = HitType.all
    @hits = @player.hits

    @at_bats = Hit.where(player_id: @player.id)
    @hits = @at_bats.reject {|x| x.hit_type_id == 1}
    @outs = Hit.where(hit_type_id: 1, player_id: @player.id).length
    @singles = Hit.where(hit_type_id: 2, player_id: @player.id).length
    @doubles = Hit.where(hit_type_id: 3, player_id: @player.id).length
    @triples = Hit.where(hit_type_id: 4, player_id: @player.id).length
    @homeruns = Hit.where(hit_type_id: 5, player_id: @player.id).length

  end

  def new
    @team = Team.find(params[:team_id])
    @player = Player.new
  end

  def create
    @team = Team.find(params[:team_id])
    @player = @team.players.new(player_params)
    if @player.save
      redirect_to team_player_path(@team, @player)
    else
      redirect_to :back
    end
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(team_id: params[:team_id])
      redirect_to :back
    else
      redirect_to :back
    end
  end



private
  def player_params
    params.require(:player).permit(:name, :photo, :team_id)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @players = Player.all
    @team = Team.find(params[:id])
    @team_players = @team.players
    @lineup = @team.lineup
    @bench_players = @team_players.where.not(id: @lineup)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to team_path(@team)
    else
      redirect_to :back
    end
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      respond_to do |format|
        format.html { redirect_to :back }
      end
    end

  end

private
  def team_params
    params.require(:team).permit(:name, :address, :logo, :stadium_chart, :lineup)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hits/_hit.html.erb
<%= link_to '', team_player_hit_path(@team, @player, @hit), method: 'delete', remote: true, class: "hit-circle #{hit.hit_type.name}", style: "top: #{hit.coords.split(',')[1]}px; left: #{hit.coords.split(',')[0]}px", id: "#{hit.id}" %>

app/views/hits/create.js.erb
$('#spray-chart').append('<%= j render(@hit) %>');

app/views/hits/destroy.js.erb
$('#spray-chart').find('#<%= @hit.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Spray Chart</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>

    <script src="http://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
    <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type"text/javascript"></script>
    <%= javascript_include_tag "application" %>
  </head>

  <body>

    <div id="wrapper">
      <%= yield %>
    </div>

  </body>
</html>

app/views/players/index.html.erb
<ul><% @players.each do |player| %>
  <li><%= link_to player.name, team_player_path(player.team, player) %></li>
<% end %>
</ul>

app/views/players/new.html.erb
<%= form_for [@team, @player] do |f| %>
  <div class="row">
    <div class="columns">
      <%= f.text_field :name, placeholder: 'Name' %>
    </div>
  </div>
  <div class="row">
    <div class="columns">
      <%= f.file_field :photo %>
    </div>
  </div>
  <div class="row">
    <div class="columns">
      <button class="button">Submit</button>
    </div>
  </div>

<% end %>

app/views/players/show.html.erb
<ul class="breadcrumbs">
  <li><%= link_to 'Home', teams_path %></li>
  <li><%= link_to @team.name, team_path(@team) %></li>
  <li class="current"><%= link_to @player.name, team_player_path(@team, @player) %></li>
</ul>

<div class="row">
  <div class="large-2 columns">
    <%= image_tag @player.photo.url(:thumb) %>
  </div>
  <div class="large-4 end columns">
    <h1><%= @player.name %></h1>
  </div>
</div>

<div class="row">
  <table class="stats-table">
    <tr><th>AB</th><th>H</th><th>BA</th><th>SLG</th><th>1B</th><th>2B</th><th>3B</th><th>HR</th></tr>
    <tr>
      <td><%= @at_bats.length %></td>
      <td><%= @hits.length %></td>
      <td><%= @player.batting_average(@hits.length, @at_bats.length) %></td>
      <td><%= @player.slugging(@singles, @doubles, @triples, @homeruns, @at_bats.length) %></td>
      <td><%= @singles %></td>
      <td><%= @doubles %></td>
      <td><%= @triples %></td>
      <td><%= @homeruns %></td>
    </tr>
  </table>
</div>

<div class="row">
  <div class="large-12 columns">
    <div id="legend">
      <h4>Legend</h4>
      <ul>
        <% @hit_types.each do |hit_type| %>
          <li class="hit-type <%= hit_type.name %>" data-hit-type-id="<%= hit_type.id %>"><%= hit_type.name %></li>
        <% end %>
      </ul>
      <select id="chart-filter">
        <option selected value="all">Show All</option>
        <option value="single">Singles</option>
        <option value="double">Doubles</option>
        <option value="triple">Triples</option>
        <option value="homerun">Homeruns</option>
        <option value="out">Outs</option>
      </select>
    </div>
    <div id="spray-chart">
      <% @hits.each do |hit| %>
        <%= link_to '', team_player_hit_path(@team, @player, hit), method: 'delete', remote: true, class: "hit-circle #{hit.hit_type.name}", style: "top: #{hit.coords.split(',')[1]}px; left: #{hit.coords.split(',')[0]}px", id: "#{hit.id}" %>
      <% end %>
    </div>
    <%= form_for [@team, @player, @hit], remote: true do |f| %>
      <%= f.hidden_field :coords, id: 'hidden-hit-coords' %>
      <%= f.hidden_field :hit_type_id, id: 'hidden-hit_type_id' %>
    <% end %>
  </div>
</div>


<script>
  $(document).ready(function(){

    $('#chart-filter').change(function(){
      selectedFilter = $('#chart-filter').val();

      $('.hit-circle').each(function(index, value) {
        $(this).hide();
        if ($(this).hasClass(selectedFilter) || selectedFilter == 'all') {
          $(this).show();
        }
      });
    });

    $('.hit-type').on('click', function() {
      $('#hidden-hit_type_id').val($(this).data('hit-type-id'));
    });

    $('#spray-chart').on('dblclick', function(e) {
      if ($('#hidden-hit_type_id').val() != '') {
        parentOffset = $(this).parent().offset();
        relX = parseInt(e.pageX - parentOffset.left) - 15;
        relY = parseInt(e.pageY - parentOffset.top);
        $('#hidden-hit-coords').val(relX + ',' + relY);
        $('#new_hit').submit();
        $('#hidden-hit_type_id').val('')
      } else {
        alert('select a hit type first!')
      }
    });

  })
</script>